// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.tsx";
import * as $2 from "./routes/api/action.ts";
import * as $3 from "./routes/api/events/game.ts";
import * as $4 from "./routes/api/events/games.ts";
import * as $5 from "./routes/auth/oauth2callback.ts";
import * as $6 from "./routes/auth/signin.ts";
import * as $7 from "./routes/auth/signout.ts";
import * as $8 from "./routes/create.tsx";
import * as $9 from "./routes/game/[id].tsx";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/GameDisplay.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.tsx": $1,
    "./routes/api/action.ts": $2,
    "./routes/api/events/game.ts": $3,
    "./routes/api/events/games.ts": $4,
    "./routes/auth/oauth2callback.ts": $5,
    "./routes/auth/signin.ts": $6,
    "./routes/auth/signout.ts": $7,
    "./routes/create.tsx": $8,
    "./routes/game/[id].tsx": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/GameDisplay.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
