import shuffle from "https://deno.land/x/shuffle@v1.0.1/mod.ts";
import { GemStone } from "🛠️/types.ts";
import type { Card } from "🛠️/types.ts";

export const cards: Card[] = [
  {
    symbol: GemStone.ONYX,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 1,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 4,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 1,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 4,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 1,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 4,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 1,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 4,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 0,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 1,
    level: 1,
    price: {
      [GemStone.DIAMOND]: 4,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 1,
      [GemStone.EMERALD]: 4,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 5,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 5,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 3,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 6,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 5,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 1,
      [GemStone.ONYX]: 4,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 5,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 3,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 6,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 1,
      [GemStone.RUBY]: 4,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 5,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 5,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 3,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 6,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 2,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 4,
      [GemStone.SAPPHIRE]: 2,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 1,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 5,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 5,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 3,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 6,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 2,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 1,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 2,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 1,
      [GemStone.SAPPHIRE]: 4,
      [GemStone.EMERALD]: 2,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 5,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 2,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 5,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 3,
    level: 2,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 6,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 3,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 5,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 7,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 6,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.ONYX,
    points: 5,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 7,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 3,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 5,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 7,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 6,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.SAPPHIRE,
    points: 5,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 7,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 3,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 5,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 7,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 6,
    },
  },
  {
    symbol: GemStone.DIAMOND,
    points: 5,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 7,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 3,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 5,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 7,
      [GemStone.EMERALD]: 0,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 6,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.EMERALD,
    points: 5,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 7,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 3,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 3,
      [GemStone.SAPPHIRE]: 5,
      [GemStone.EMERALD]: 3,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 3,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 7,
      [GemStone.RUBY]: 0,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 4,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 3,
      [GemStone.EMERALD]: 6,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
  {
    symbol: GemStone.RUBY,
    points: 5,
    level: 3,
    price: {
      [GemStone.DIAMOND]: 0,
      [GemStone.SAPPHIRE]: 0,
      [GemStone.EMERALD]: 7,
      [GemStone.RUBY]: 3,
      [GemStone.ONYX]: 0,
    },
  },
];

const cardsBy = (givenCards: Card[], level: Card["level"]): Card[] => {
  return givenCards.filter((card) => card.level === level);
};

export const separateCards = (
  givenCards: Card[],
): Map<Card["level"], Card[]> => {
  return new Map([
    [1, cardsBy(givenCards, 1)] as const,
    [2, cardsBy(givenCards, 2)] as const,
    [3, cardsBy(givenCards, 3)] as const,
  ]);
};

export const prepareCards = (
  givenCards: Card[],
): Map<Card["level"], Card[]> => {
  const shuffledCards = shuffle(givenCards);

  return separateCards(shuffledCards);
};
